kind: ClusterIssuer
apiVersion: cert-manager.io/v1
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Use Let's Encrypt staging server
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: shubhamnath5@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
    - http01:
        ingress:
          class: nginx
